### ISSUE TITLE
Docker Compose Up script

### ISSUE THREAD

**Issue by sultanadeel** [mschermann/dataviz_docker#1]
Hi, i installed Docker Toolbox for my Windows machine and then cloned the repository to a local folder. Subsequently, when i am trying to build the docker container using docker-compose up command, it's not executing the script. Attached is the snapshot of the command prompt
<img width="594" alt="docker-compose" src="https://user-images.githubusercontent.com/31932632/30628453-3cf135ee-9d8b-11e7-80d6-c8bbdafbc665.PNG">

**Comment by mschermann** [comment]
Can you run `docker-compose --version`. Also run `docker-compose up --help`. Do you get error messages?

**Comment by mschermann** [comment]
Also, check this out: https://github.com/docker/compose/issues/5044#issuecomment-316825646

**Comment by sultanadeel** [comment]
Hi Dr Schermann,

I don't get error messages when i run both docker-compose --version and
docker-compose up --help. However when i run docker-compose up, it
generates an error. Thanks for your help

Regards

Muhammad

**Comment by mschermann** [comment]
Check this please: https://github.com/mschermann/dataviz_docker/issues/1#issuecomment-330761287

**Comment by mschermann** [comment]
Clone again and see if it works now @sultanadeel

**Comment by PriyankaN22** [comment]
Hi Professor,
I am also facing the issue with docker-compose up. Please refer the screenshot below.

![docker issue](https://user-images.githubusercontent.com/31669563/30681395-283f782a-9e5a-11e7-8a77-fbf224b26461.JPG)

I checked few threads for resolution, it seems I need to reset factory defaults every time to get docker to run. 

I just wanted to check if you know any other resolution for this. 

Appreciate your help!

-Priyanka

**Comment by sultanadeel** [comment]
Hi Dr Schermann,

I cloned again to a different folder and reinstalled Docker toolbox and ran
the script in docker terminal, however, it's showing again the same error
as follows

[image: Inline image 1]

Thanks & Regards

On Wed, Sep 20, 2017 at 9:55 PM, Michael Schermann <notifications@github.com

**Comment by mschermann** [comment]
@priyankad228 make sure that you run the docker-compose up in the directory where you cloned the repository to (Make sure that the directory contains the docker-compose.yml)

**Comment by mschermann** [comment]
@sultanadeel 
1. Create a new folder
2. Create a file in this folder called 'Dockerfile'
3. Copy the following lines into this file
```
FROM python:3
RUN apt-get update -y 
RUN apt-get install -y apt-utils
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
```
4. Run the following command in this folder:
`docker . build`

What is the output?

**Comment by sultanadeel** [comment]
Hi Dr Schermann, i followed the above steps, created a folder with a text file having the above script, and then used Docker Terminal to run docker . build command. However, it is not able to read the file somehow. I am trying to read the file using the build command. Thanks

**Comment by mschermann** [comment]
@sultanadeel What is the error message?

**Comment by sultanadeel** [comment]
The error message is as follows
[image: Inline image 1]

**Comment by mschermann** [comment]
@sultanadeel no image?

**Comment by sultanadeel** [comment]
<img width="406" alt="capture 2" src="https://user-images.githubusercontent.com/31932632/30716063-798504e8-9ecd-11e7-9e07-16206f931184.PNG">

**Comment by mschermann** [comment]
The command is `docker . build`. Please note the spaces before and after the .

**Comment by PriyankaN22** [comment]
I installed Docker Toolbox and executed the commands using docker terminal, the error I was getting earlier is resolved. Now I get the same error as Adeel is getting. I followed the instructions and got this.
![image](https://user-images.githubusercontent.com/31669563/30717362-8e2c69dc-9ed1-11e7-82ef-7b779c13c7bc.png)

**Comment by mschermann** [comment]
Ha, dang. I was too quick. The command is `docker build .` Sorry!

**Comment by bhargavre** [comment]
Hello Professor,

I am also facing similar issues and have been following your steps suggested to Adeel and Priyanka
In response to your last comment, i received the following error.

![image](https://user-images.githubusercontent.com/32179171/30718775-e4bc905c-9ed5-11e7-9b89-5daded72e90b.png)

**Comment by mschermann** [comment]
@bhargavre Are you in the same directory? Have you name the file Dockerfile without any endings?

**Comment by bhargavre** [comment]
Yes. I created a file "Dockerfile" and am in the same directory.

**Comment by mschermann** [comment]
try the following `docker build . --file ./Dockerfile`
Also, check the Dockerfile - typically Windows adds a file-ending such as .txt

**Comment by bhargavre** [comment]
So the file is a text file. Should I save it with another extension?
This time i got the below message

![image](https://user-images.githubusercontent.com/32179171/30719215-7b27f0bc-9ed7-11e7-9d90-5b7e9ce5f089.png)

**Comment by mschermann** [comment]
@bhargavre That is what I thought. Try `docker build . --file ./Dockerfile.txt`

**Comment by bhargavre** [comment]
Similar message

![image](https://user-images.githubusercontent.com/32179171/30719299-d272c946-9ed7-11e7-8778-cf97c78af569.png)

**Comment by bhargavre** [comment]
oops sorry.

![image](https://user-images.githubusercontent.com/32179171/30719341-fa21ce06-9ed7-11e7-9fa1-b92d8d248ad8.png)

**Comment by mschermann** [comment]
@bhargavre It seems that you have copied all the code in one line? This should be separate lines
```
FROM python:3
RUN apt-get update -y 
RUN apt-get install -y apt-utils
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
```

**Comment by bhargavre** [comment]
I changed it to separate lines and then worked only till Get 7:
The following message appeared

![image](https://user-images.githubusercontent.com/32179171/30719564-d43bd4ec-9ed8-11e7-9cdf-09032003c08f.png)

**Comment by mschermann** [comment]
But this is just a warning...

Try the original dataviz_docker again...

**Comment by mschermann** [comment]
do you have access to the system?

**Comment by bhargavre** [comment]
Yes i have access to the system,

and below is the entire message

![image](https://user-images.githubusercontent.com/32179171/30719656-290ea094-9ed9-11e7-82a8-bc72615d9bc1.png)

**Comment by mschermann** [comment]
ok.. it seems to work. Now, follow the instructions here: https://github.com/mschermann/dataviz_docker

**Comment by bhargavre** [comment]
So now the last step it reached was 7/26. and below is the message

![image](https://user-images.githubusercontent.com/32179171/30719775-ab728fc8-9ed9-11e7-9e07-8d378f463d96.png)

**Comment by mschermann** [comment]
@bhargavre I guess this is a windows issue. Try to run it in the Docker Quickstart Terminal that comes with the Docker installation on Windows...

**Comment by bhargavre** [comment]
This is actually on the Docker Quickstart Terminal itself.

So when we launch the terminal. i enter cmd and follow the instructions

**Comment by mschermann** [comment]
I released a new version, pull, and try again.

**Comment by PriyankaN22** [comment]
I tried with new version. It's still producing the same error as Bhargav mentioned

**Comment by mschermann** [comment]
If you are around, just stop by. Otherwise, install jupyter without the docker (see the FAQ) for now.

**Comment by PriyankaN22** [comment]
got this error at the end

![image](https://user-images.githubusercontent.com/31669563/30730746-22c7a5ce-9f1e-11e7-9d27-504c593cbab7.png)

**Comment by thomasdere** [comment]
Windows Users ...
Good news and bad news:
Good news is that I finally was able to install it on Windows 10 after initially receiving the same errors you have listed above.
Bad news is that Windows 10 "Home" Edition appears to be incompatible with Docker. After upgrading from Windows 10 "Home" to Windows 10 "Pro", I was able to get everything to work. Unfortunately, Windows 10 Pro upgrade is not free and ranges from $179-$199. Hopefully the Professor has some alternatives for Windows Users.
The other error where I ran into difficulty was at Step 1. "Clone this repository to a folder". This step didn't appear to extract all of the files to the directory provided. The fix for me was to create a zip file and unzip the contents instead of using the clone method of the git repository. Once you confirm that the individual files are there, you can then run the "docker-compose up" command to complete the installation.
Lastly, the provided URL didn't work with the "0.0.0.0", but I was able to replace that portion with "localhost" and the jupyter notebook screen then appeared in the browser.

**Comment by mschermann** [comment]
To all Windows users: please try to install jupyter as described here: http://jupyter.org/install.html

**Comment by mschermann** [comment]
@PriyankaN22 try this: https://github.com/docker/labs/issues/215#issuecomment-304596295
