### ISSUE TITLE
Loading the xls file in jupyter

### ISSUE THREAD

**Issue by Ritusani** [mschermann/dataviz_docker#2]
I have tried multiple scripts to load the data into jupyter. Could you please me to resolve this issue?

**Comment by Ritusani** [comment]
Following link has the steps that I tried recently - https://dev.socrata.com/blog/2016/02/01/pandas-and-jupyter-notebook.html

**Comment by mschermann** [comment]
What is the error message?

**Comment by mschermann** [comment]
you have to install additional packages...
