### ISSUE TITLE
no xlsxwriter or openpyxl module

### ISSUE THREAD

**Issue by nrajeswaran** [mschermann/dataviz_docker#3]
Hi Professor,

I am unable to write the cleaned data into an excel using xlsxwriter/ openpyxl modules, it throws the ModuleNotFoundError.

Please find below the screenshots for the same. 

![image](https://user-images.githubusercontent.com/32077623/30766877-ef543966-9fac-11e7-808e-451af5cd4933.png)
![image](https://user-images.githubusercontent.com/32077623/30766896-0a68611e-9fad-11e7-94bf-1f0d0f7351c6.png)

Thanks,
Nandini

**Comment by mschermann** [comment]
The container only includes the basic packages. You can install packages in two ways:
```
!pip install package-name
```
or add the package to the file requirements.txt and run
```
docker-compose up --build
```

**Comment by nrajeswaran** [comment]
Thanks professor!
